### ISSUE TITLE
SimpleDB deprecation

### ISSUE THREAD

**Issue by davidkhala** [squidfunk/isotopes#669]
## Description

As titled, simpleDB in aws is deprecated and not available in most of cases (new regions or new accounts). While this project looks young still, should it be bump to any current available alternative like DynamoDB?

### Expected behavior

Document updates and new release (could be a breaking change one)

**Comment by squidfunk** [comment]
Thanks for suggesting. No plans to do that, since DynamoDB has entirely different semantics. SimpleDB has been deprecated for 10+ years and it's still working in many accounts. If you're in a region that supports it, this project is for you. Otherwise, you should probably use another library.
